// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoO_GLedUgsIgANTtSH9bcAHEAutGngA',
    appId: '1:872448302334:web:7b81d51076250db70d99af',
    messagingSenderId: '872448302334',
    projectId: 'travelloom-d985e',
    authDomain: 'travelloom-d985e.firebaseapp.com',
    storageBucket: 'travelloom-d985e.firebasestorage.app',
    measurementId: 'G-5JKSD688E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMtUpokHv7o3UTfjW6OG8kp-j8w2If5Us',
    appId: '1:872448302334:android:68e47e3b964a145f0d99af',
    messagingSenderId: '872448302334',
    projectId: 'travelloom-d985e',
    storageBucket: 'travelloom-d985e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQeQSKVNUgLvwjbN8y00L7iCm_V8ugCs',
    appId: '1:872448302334:ios:79e74a4072160bb10d99af',
    messagingSenderId: '872448302334',
    projectId: 'travelloom-d985e',
    storageBucket: 'travelloom-d985e.firebasestorage.app',
    iosBundleId: 'com.example.travelLoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXQeQSKVNUgLvwjbN8y00L7iCm_V8ugCs',
    appId: '1:872448302334:ios:79e74a4072160bb10d99af',
    messagingSenderId: '872448302334',
    projectId: 'travelloom-d985e',
    storageBucket: 'travelloom-d985e.firebasestorage.app',
    iosBundleId: 'com.example.travelLoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnoO_GLedUgsIgANTtSH9bcAHEAutGngA',
    appId: '1:872448302334:web:527c6ff1a4576d720d99af',
    messagingSenderId: '872448302334',
    projectId: 'travelloom-d985e',
    authDomain: 'travelloom-d985e.firebaseapp.com',
    storageBucket: 'travelloom-d985e.firebasestorage.app',
    measurementId: 'G-ZSN68661B7',
  );
}
